version: "3"
services:
  pacs:
    container_name: orthanc
    image: jodogne/orthanc-plugins
    ports:
      - 8042:8042
      - 4242:4242
    volumes:
      - ./orthanc.json:/etc/orthanc/orthanc.json:ro
      - ./orthanc_db:/var/lib/orthanc/db/
    restart: always



